language: generic

sudo: required

services:
  - docker

before-install:
  - docker build -t tarunsingh/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true tarunsingh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-875632962180"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
